### ISSUE TITLE
[1.20.1 BUG] Solar Panels still produce if it's night

### ISSUE THREAD

**Issue by MundM2007** [Pocky-l/Mekanism-MoreSolarPanels#5]
Idk if it's intended, but probably not, because the display inside of the solar panel says it produces 0FE but it actually still increases in energy. This may affect other versions aswell.

**Comment by Pocky-l** [comment]
Hi, thx for the report. The data was displaying incorrectly within the GUI panels. Regarding energy production at night, that was intentional, but the panels produce energy much less efficiently during that time.
I've fixed the error in the GUI, please download the new version of the mod.
If you have any questions, feel free to create new issues. Thx.

**Comment by MundM2007** [comment]
If possible it May be better to Just add a config Option that allows you to set the percentage of efficiency during night AS this behaviour is almosta lready completely integrated into your mod. (decrease efficiency at night)
